### ISSUE TITLE
Error in re-creating sciplex analysis

### ISSUE THREAD

**Issue by DanLesman** [nitzanlab/biolord_reproducibility#2] opened 2024-02-22 03:17 UTC
Hello, when running this section of code from 2_perturbations_sciplex3_evaluation.ipynb

model = biolord.Biolord(
    adata=adata,
    n_latent=256,
    model_name="sciplex3",
    module_params=module_params,
    train_classifiers=False,
    split_key="split_ood",
)

I ran into the following error:

TypeError                                 Traceback (most recent call last)
Cell In[10], line 1
----> 1 model = biolord.Biolord(
      2     adata=adata,
      3     n_latent=256,
      4     model_name="sciplex3",
      5     module_params=module_params,
      6     train_classifiers=False,
      7     split_key="split_ood",
      8 )

File /lib/python3.9/site-packages/biolord/_model.py:137, in Biolord.__init__(self, adata, model_name, module_params, n_latent, train_classifiers, split_key, train_split, valid_split, test_split)
    126     self.module = BiolordClassifyModule(
    127         n_genes=self.n_genes,
    128         n_samples=self.n_samples,
   (...)
    134         **module_params,
    135     ).float()
    136 else:
--> 137     self.module = BiolordModule(
    138         n_genes=self.n_genes,
    139         n_samples=self.n_samples,
    140         x_loc=self.x_loc,
    141         ordered_attributes_map=self.ordered_attributes_map,
    142         categorical_attributes_map=self.categorical_attributes_map,
    143         n_latent=self.n_latent,
    144         **module_params,
    145     ).float()
    147 self._model_summary_string = self.__class__.__name__
    148 self._model_name = model_name

TypeError: __init__() got an unexpected keyword argument 'loss_ae'

Thank you so much for making this tool and your code available!

**Comment by zoepiran** [comment] 2024-04-11 15:30
Hi, 

Please excuse the late response! 
We have just pushed a fix for this repo that shall resolve this.

**Closed as completed by zoepiran** 2024-04-11 15:30 UTC

**Comment by DanLesman** [comment] 2024-04-25 01:38
I'm now getting a new bug. I think it may be useful if there was a fille that outlined the versions of packages used. For example, chemprop is now version 2 by default, so to get proper featurization I needed to pip install chemprop==1.6.1.

When I run the following line of code:

model.train(
    max_epochs=200,
    batch_size=512,
    plan_kwargs=trainer_params,
    early_stopping=True,
    early_stopping_patience=20,
    check_val_every_n_epoch=10,
    num_workers=1,
)

I get this error:

/orcd/archive/001/Projects/dlesman/biolord_env/lib/python3.12/site-packages/lightning/fabric/plugins/environments/slurm.py:191](http://127.0.0.1:8890/orcd/archive/001/Projects/dlesman/biolord_env/lib/python3.12/site-packages/lightning/fabric/plugins/environments/slurm.py#line=190): The `srun` command is available on your system but is not used. HINT: If your intention is to run Lightning on SLURM, prepend your python command with `srun` like so: srun python [/orcd/archive/001/Projects/dlesman/biolord_e](http://127.0.0.1:8890/orcd/archive/001/Projects/dlesman/biolord_e) 
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
[/orcd/archive/001/Projects/dlesman/biolord_env/lib/python3.12/site-packages/lightning/fabric/plugins/environments/slurm.py:191](http://127.0.0.1:8890/orcd/archive/001/Projects/dlesman/biolord_env/lib/python3.12/site-packages/lightning/fabric/plugins/environments/slurm.py#line=190): The `srun` command is available on your system but is not used. HINT: If your intention is to run Lightning on SLURM, prepend your python command with `srun` like so: srun python [/orcd/archive/001/Projects/dlesman/biolord_e](http://127.0.0.1:8890/orcd/archive/001/Projects/dlesman/biolord_e) ...
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
[/orcd/archive/001/Projects/dlesman/biolord_env/lib/python3.12/multiprocessing/popen_fork.py:66](http://127.0.0.1:8890/orcd/archive/001/Projects/dlesman/biolord_env/lib/python3.12/multiprocessing/popen_fork.py#line=65): RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
Epoch 1/200:   0%| | 1/200 [00:33<1:49:27, 33.00s/it, v_num=1, val_generative_mean_accuracy=0.492, val_generative_var_accuracy=-3.87, val_biolord_metric=-1.69, val_LO
[/orcd/archive/001/Projects/dlesman/biolord_env/lib/python3.12/multiprocessing/popen_fork.py:66](http://127.0.0.1:8890/orcd/archive/001/Projects/dlesman/biolord_env/lib/python3.12/multiprocessing/popen_fork.py#line=65): RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()

MisconfigurationException                 Traceback (most recent call last)
Cell In[15], line 1
----> 1 model.train(
      2     max_epochs=200,
      3     batch_size=512,
      4     plan_kwargs=trainer_params,
      5     early_stopping=True,
      6     early_stopping_patience=20,
      7     check_val_every_n_epoch=10,
      8     num_workers=1,
      9 )

File [/orcd/archive/001/Projects/dlesman/biolord_env/lib/python3.12/site-packages/biolord/_model.py:729](http://127.0.0.1:8890/orcd/archive/001/Projects/dlesman/biolord_env/lib/python3.12/site-packages/biolord/_model.py#line=728), in Biolord.train(self, max_epochs, accelerator, device, train_size, validation_size, plan_kwargs, batch_size, early_stopping, **trainer_kwargs)
    714 trainer_kwargs["default_root_dir"] = trainer_kwargs.pop("default_root_dir", root_dir)
    716 runner = TrainRunner(
    717     self,
    718     training_plan=self.training_plan,
   (...)
    726     **trainer_kwargs,
    727 )
--> 729 return runner()

File [/orcd/archive/001/Projects/dlesman/biolord_env/lib/python3.12/site-packages/scvi/train/_trainrunner.py:98](http://127.0.0.1:8890/orcd/archive/001/Projects/dlesman/biolord_env/lib/python3.12/site-packages/scvi/train/_trainrunner.py#line=97), in TrainRunner.__call__(self)
     95 if hasattr(self.data_splitter, "n_val"):
     96     self.training_plan.n_obs_validation = self.data_splitter.n_val
---> 98 self.trainer.fit(self.training_plan, self.data_splitter)
     99 self._update_history()
    101 # data splitter only gets these attrs after fit

File [/orcd/archive/001/Projects/dlesman/biolord_env/lib/python3.12/site-packages/scvi/train/_trainer.py:219](http://127.0.0.1:8890/orcd/archive/001/Projects/dlesman/biolord_env/lib/python3.12/site-packages/scvi/train/_trainer.py#line=218), in Trainer.fit(self, *args, **kwargs)
    213 if isinstance(args[0], PyroTrainingPlan):
    214     warnings.filterwarnings(
    215         action="ignore",
    216         category=UserWarning,
    217         message="`LightningModule.configure_optimizers` returned `None`",
    218     )
--> 219 super().fit(*args, **kwargs)

File [/orcd/archive/001/Projects/dlesman/biolord_env/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py:544](http://127.0.0.1:8890/orcd/archive/001/Projects/dlesman/biolord_env/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py#line=543), in Trainer.fit(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    542 self.state.status = TrainerStatus.RUNNING
    543 self.training = True
--> 544 call._call_and_handle_interrupt(
    545     self, self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
    546 )

File [/orcd/archive/001/Projects/dlesman/biolord_env/lib/python3.12/site-packages/lightning/pytorch/trainer/call.py:44](http://127.0.0.1:8890/orcd/archive/001/Projects/dlesman/biolord_env/lib/python3.12/site-packages/lightning/pytorch/trainer/call.py#line=43), in _call_and_handle_interrupt(trainer, trainer_fn, *args, **kwargs)
     42     if trainer.strategy.launcher is not None:
     43         return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
---> 44     return trainer_fn(*args, **kwargs)
     46 except _TunerExitException:
     47     _call_teardown_hook(trainer)

File [/orcd/archive/001/Projects/dlesman/biolord_env/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py:580](http://127.0.0.1:8890/orcd/archive/001/Projects/dlesman/biolord_env/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py#line=579), in Trainer._fit_impl(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    573 assert self.state.fn is not None
    574 ckpt_path = self._checkpoint_connector._select_ckpt_path(
    575     self.state.fn,
    576     ckpt_path,
    577     model_provided=True,
    578     model_connected=self.lightning_module is not None,
    579 )
--> 580 self._run(model, ckpt_path=ckpt_path)
    582 assert self.state.stopped
    583 self.training = False

File [/orcd/archive/001/Projects/dlesman/biolord_env/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py:989](http://127.0.0.1:8890/orcd/archive/001/Projects/dlesman/biolord_env/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py#line=988), in Trainer._run(self, model, ckpt_path)
    984 self._signal_connector.register_signal_handlers()
    986 # ----------------------------
    987 # RUN THE TRAINER
    988 # ----------------------------
--> 989 results = self._run_stage()
    991 # ----------------------------
    992 # POST-Training CLEAN UP
    993 # ----------------------------
    994 log.debug(f"{self.__class__.__name__}: trainer tearing down")

File [/orcd/archive/001/Projects/dlesman/biolord_env/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py:1035](http://127.0.0.1:8890/orcd/archive/001/Projects/dlesman/biolord_env/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py#line=1034), in Trainer._run_stage(self)
   1033         self._run_sanity_check()
   1034     with torch.autograd.set_detect_anomaly(self._detect_anomaly):
-> 1035         self.fit_loop.run()
   1036     return None
   1037 raise RuntimeError(f"Unexpected state {self.state}")

File [/orcd/archive/001/Projects/dlesman/biolord_env/lib/python3.12/site-packages/lightning/pytorch/loops/fit_loop.py:203](http://127.0.0.1:8890/orcd/archive/001/Projects/dlesman/biolord_env/lib/python3.12/site-packages/lightning/pytorch/loops/fit_loop.py#line=202), in _FitLoop.run(self)
    201     self.on_advance_start()
    202     self.advance()
--> 203     self.on_advance_end()
    204     self._restarting = False
    205 except StopIteration:

File [/orcd/archive/001/Projects/dlesman/biolord_env/lib/python3.12/site-packages/lightning/pytorch/loops/fit_loop.py:374](http://127.0.0.1:8890/orcd/archive/001/Projects/dlesman/biolord_env/lib/python3.12/site-packages/lightning/pytorch/loops/fit_loop.py#line=373), in _FitLoop.on_advance_end(self)
    372 call._call_callback_hooks(trainer, "on_train_epoch_end", monitoring_callbacks=False)
    373 call._call_lightning_module_hook(trainer, "on_train_epoch_end")
--> 374 call._call_callback_hooks(trainer, "on_train_epoch_end", monitoring_callbacks=True)
    376 trainer._logger_connector.on_epoch_end()
    378 if self.epoch_loop._num_ready_batches_reached():
    379     # if we are restarting and the above condition holds, it's because we are reloading an epoch-end checkpoint.
    380     # since metric-based schedulers require access to metrics and those are not currently saved in the
    381     # checkpoint, the plateau schedulers shouldn't be updated

File [/orcd/archive/001/Projects/dlesman/biolord_env/lib/python3.12/site-packages/lightning/pytorch/trainer/call.py:208](http://127.0.0.1:8890/orcd/archive/001/Projects/dlesman/biolord_env/lib/python3.12/site-packages/lightning/pytorch/trainer/call.py#line=207), in _call_callback_hooks(trainer, hook_name, monitoring_callbacks, *args, **kwargs)
    206     if callable(fn):
    207         with trainer.profiler.profile(f"[Callback]{callback.state_key}.{hook_name}"):
--> 208             fn(trainer, trainer.lightning_module, *args, **kwargs)
    210 if pl_module:
    211     # restore current_fx when nested context
    212     pl_module._current_fx_name = prev_fx_name

File [/orcd/archive/001/Projects/dlesman/biolord_env/lib/python3.12/site-packages/lightning/pytorch/callbacks/model_checkpoint.py:313](http://127.0.0.1:8890/orcd/archive/001/Projects/dlesman/biolord_env/lib/python3.12/site-packages/lightning/pytorch/callbacks/model_checkpoint.py#line=312), in ModelCheckpoint.on_train_epoch_end(self, trainer, pl_module)
    311 monitor_candidates = self._monitor_candidates(trainer)
    312 if self._every_n_epochs >= 1 and (trainer.current_epoch + 1) % self._every_n_epochs == 0:
--> 313     self._save_topk_checkpoint(trainer, monitor_candidates)
    314 self._save_last_checkpoint(trainer, monitor_candidates)

File [/orcd/archive/001/Projects/dlesman/biolord_env/lib/python3.12/site-packages/lightning/pytorch/callbacks/model_checkpoint.py:368](http://127.0.0.1:8890/orcd/archive/001/Projects/dlesman/biolord_env/lib/python3.12/site-packages/lightning/pytorch/callbacks/model_checkpoint.py#line=367), in ModelCheckpoint._save_topk_checkpoint(self, trainer, monitor_candidates)
    362     m = (
    363         f"`ModelCheckpoint(monitor={self.monitor!r})` could not find the monitored key in the returned"
    364         f" metrics: {list(monitor_candidates)}."
    365         f" HINT: Did you call `log({self.monitor!r}, value)` in the `LightningModule`?"
    366     )
    367     if trainer.fit_loop.epoch_loop.val_loop._has_run:
--> 368         raise MisconfigurationException(m)
    369     warning_cache.warn(m)
    370 self._save_monitor_checkpoint(trainer, monitor_candidates)

MisconfigurationException: `ModelCheckpoint(monitor='validation_loss')` could not find the monitored key in the returned metrics: ['val_generative_mean_accuracy', 'val_generative_var_accuracy', 'val_biolord_metric', 'val_LOSS_KEYS.RECONSTRUCTION', 'val_LOSS_KEYS.UNKNOWN_ATTRIBUTE_PENALTY', 'generative_mean_accuracy', 'generative_var_accuracy', 'biolord_metric', <LOSS_KEYS.RECONSTRUCTION: 'reconstruction_loss'>, <LOSS_KEYS.UNKNOWN_ATTRIBUTE_PENALTY: 'unknown_attribute_penalty_loss'>, 'epoch', 'step']. HINT: Did you call `log('validation_loss', value)` in the `LightningModule`?

**Comment by zoepiran** [comment] 2024-04-25 13:55
Hi, 
Please excuse us, we have the [requirements.txt](https://github.com/nitzanlab/biolord_reproducibility/blob/main/requirements.txt) file which lists packages and i realize that `chemprop` is indeed not there. With that we provide the processed `anndata` files which contains the required features. 

I am afraid your issue is also due to some sort of incompatibility between lightning and scvi, what are the versions you are using? 
Also, can you try uninstalling jax from the environment?

**Comment by DanLesman** [comment] 2024-04-25 15:04
Hi,

Thank you for getting back to me! I am now going through the requirements.txt file. It seems that there are some issues with the versions used, like I've gotten these errors so far:
ERROR: Could not find a version that satisfies the requirement alembic==1.4.3.dev0
ERROR: Could not find a version that satisfies the requirement arandr==0.1.10 (from versions: none)

I was wondering if you could let me know which python version I should be using?

**Comment by DanLesman** [comment] 2024-04-25 15:05
Nevermind, I found that it's 3.9.2, will continue trying to get the requirements to install

**Comment by DanLesman** [comment] 2024-04-26 16:13
So the requirements.txt file is not working properly. I run into several issues. To try and get the run to skip over the failing package installations (which happens once every 5-10 packages) I tried cat requirements.txt | xargs -n 1 pip install. But as this runs, eventually pip breaks and I get the following error for all the remaining packages:

Error processing line 1 of /orcd/archive/abugoot/001/Projects/dlesman/biolord_env_new/lib/python3.9/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "/orcd/archive/abugoot/001/Projects/dlesman/biolord_env_new/lib/python3.9/site.py", line 177, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Pleaset let me know if additional info would be helpful.

**Comment by zoepiran** [comment] 2024-04-26 16:25
Please excuse us for this inconvenience. 
Can you please try starting a python 3.9.2 with installation of `biolord` (+`seaborn`, `umap`) in the environment.

**Comment by DanLesman** [comment] 2024-04-26 18:44
I tried and got this error (same as before):
MisconfigurationException: `ModelCheckpoint(monitor='validation_loss')` could not find the monitored key in the returned metrics: ['val_generative_mean_accuracy', 'val_generative_var_accuracy', 'val_biolord_metric', 'val_reconstruction_loss', 'val_unknown_attribute_penalty_loss', 'generative_mean_accuracy', 'generative_var_accuracy', 'biolord_metric', <LOSS_KEYS.RECONSTRUCTION: 'reconstruction_loss'>, <LOSS_KEYS.UNKNOWN_ATTRIBUTE_PENALTY: 'unknown_attribute_penalty_loss'>, 'epoch', 'step']. HINT: Did you call `log('validation_loss', value)` in the `LightningModule`?

Here is the output to pip freeze:
absl-py==2.1.0
accumulation-tree==0.6.2
aiohttp==3.9.5
aiosignal==1.3.1
anndata==0.10.7
anyio==4.3.0
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
array_api_compat==1.6
arrow==1.3.0
asttokens==2.4.1
async-lru==2.0.4
async-timeout==4.0.3
attrs==23.2.0
Babel==2.14.0
backoff==2.2.1
beautifulsoup4==4.12.3
biolord==0.0.3
bleach==6.1.0
blessed==1.20.0
certifi==2024.2.2
cffi==1.16.0
charset-normalizer==3.3.2
chex==0.1.86
comm==0.2.2
contextlib2==21.6.0
contourpy==1.2.1
cycler==0.12.1
debugpy==1.8.1
decorator==5.1.1
defusedxml==0.7.1
dm-tree==0.1.8
docrep==0.3.2
etils==1.5.2
exceptiongroup==1.2.1
executing==2.0.1
fastjsonschema==2.19.1
filelock==3.13.4
flax==0.8.2
fonttools==4.51.0
fqdn==1.5.1
frozenlist==1.4.1
fsspec==2024.3.1
get-annotations==0.1.2
h11==0.14.0
h5py==3.11.0
httpcore==1.0.5
httpx==0.27.0
idna==3.7
importlib_metadata==7.1.0
importlib_resources==6.4.0
ipykernel==6.29.4
ipython==8.18.1
isoduration==20.11.0
jax==0.4.26
jaxlib==0.4.26
jedi==0.19.1
Jinja2==3.1.3
joblib==1.4.0
json5==0.9.25
jsonpointer==2.4
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
jupyter-events==0.10.0
jupyter-lsp==2.2.5
jupyter_client==8.6.1
jupyter_core==5.7.2
jupyter_server==2.14.0
jupyter_server_terminals==0.5.3
jupyterlab==4.1.7
jupyterlab_pygments==0.3.0
jupyterlab_server==2.27.1
kaggle==1.5.16
kiwisolver==1.4.5
legacy-api-wrap==1.4
lightning==2.1.4
lightning-utilities==0.11.2
llvmlite==0.42.0
loompy==3.0.7
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.8.4
matplotlib-inline==0.1.7
mdurl==0.1.2
mistune==3.0.2
ml-collections==0.1.1
ml-dtypes==0.4.0
mpmath==1.3.0
msgpack==1.0.8
mudata==0.2.3
multidict==6.0.5
multipledispatch==1.0.0
natsort==8.4.0
nbclient==0.10.0
nbconvert==7.16.3
nbformat==5.10.4
nest-asyncio==1.6.0
networkx==3.2.1
notebook==7.1.3
notebook_shim==0.2.4
numba==0.59.1
numpy==1.26.4
numpy-groupies==0.10.2
numpyro==0.14.0
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.20.5
nvidia-nvjitlink-cu12==12.4.127
nvidia-nvtx-cu12==12.1.105
opt-einsum==3.3.0
optax==0.2.2
orbax-checkpoint==0.5.10
ordered-set==4.1.0
overrides==7.7.0
packaging==24.0
pandas==2.2.2
pandocfilters==1.5.1
parso==0.8.4
patsy==0.5.6
pexpect==4.9.0
pillow==10.3.0
platformdirs==4.2.1
prometheus_client==0.20.0
prompt-toolkit==3.0.43
protobuf==5.26.1
psutil==5.9.8
ptyprocess==0.7.0
pure-eval==0.2.2
pycparser==2.22
Pygments==2.17.2
pynndescent==0.5.12
pyparsing==3.1.2
pyro-api==0.1.2
pyro-ppl==1.9.0
python-dateutil==2.9.0.post0
python-editor==1.0.4
python-json-logger==2.0.7
python-multipart==0.0.6
pytorch-lightning==2.2.3
pytz==2024.1
pyudorandom==1.0.0
PyYAML==6.0.1
pyzmq==26.0.2
readchar==4.0.5
referencing==0.35.0
requests==2.31.0
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rich==13.7.1
rpds-py==0.18.0
scanpy==1.10.1
scikit-learn==1.4.2
scipy==1.13.0
scvi-tools==1.1.2
seaborn==0.13.2
Send2Trash==1.8.3
session-info==1.0.0
six==1.16.0
sniffio==1.3.1
soupsieve==2.5
stack-data==0.6.3
statsmodels==0.14.2
stdlib-list==0.10.0
sympy==1.12
tdigest==0.5.2.2
tensorstore==0.1.57
terminado==0.18.1
threadpoolctl==3.4.0
tinycss2==1.3.0
tomli==2.0.1
toolz==0.12.1
torch==2.3.0
torchmetrics==1.3.2
tornado==6.4
tqdm==4.66.2
traitlets==5.14.3
triton==2.3.0
types-python-dateutil==2.9.0.20240316
typing_extensions==4.11.0
tzdata==2024.1
umap==0.1.1
umap-learn==0.5.6
uri-template==1.3.0
urllib3==2.2.1
wcwidth==0.2.13
webcolors==1.13
webencodings==0.5.1
websocket-client==1.8.0
yarl==1.9.4
zipp==3.18.1

**Comment by zoepiran** [comment] 2024-04-26 20:57
Hi Dan,
Please excuse us; this is indeed an error stemming from changes in `scvi-tools` checkpointing policy which required a modification in the `biolord` package.
We have just pushed a fix to `biolord` to resolve it. We will soon release a new version with this fix.

Locally you can simply add `enable_checkpointing=False` to the `model.train()` call:
```
model.train(
    max_epochs=200,
    batch_size=512,
    plan_kwargs=trainer_params,
    early_stopping=True,
    early_stopping_patience=20,
    check_val_every_n_epoch=10,
    num_workers=1,
    enable_checkpointing=False
)
```

For complete compatibility you shall pull the `biolord` repo or downgrade  `scvi-tools <= 1.0.4`.

Please excuse us again for this inconvenience and thank you for spotting it.

**Comment by DanLesman** [comment] 2024-04-27 18:58
Thank you! The new version works now (pip install from the main branch). I was wondering if a method was already implemented for saving and loading model weights.

**Comment by zoepiran** [comment] 2024-04-28 10:16
Yes; we generally follow scVI (lightning API) here with the `save()` and load functions (see [here](https://github.com/nitzanlab/biolord/blob/921bde6891a5db2b17a45bbb63e3a2ba7d5feaff/src/biolord/_model.py#L527-L609)). 
For saving you can also use checkpointing.

```
# save
model.save(dir_path="your_path", overwrite:bool=.., save_anndata:bool=..)

# load
biolord.Biolord.setup_anndata(adata, ...)  # following the setup of the model
biolord.Biolord.load(dir_path="your_path")
```

**Comment by DanLesman** [comment] 2024-07-26 05:13
Hi again! Thank you for all the help, another quick question. In the file "1_perturbations_adamson_preprocessing.ipynb"  you have the following line:

subgroup_analysis[seed], subgroup_analysis_deeper, test_metrics = gears_model.train(epochs = epoch)

which gives me an error because gears_model.train(epochs=epoch) does not return anything for me. Did you modify the GEARS code so that it returned something? And if so, could you provide an example or let me know what you have it returning?

Thank you!

**Comment by mlrapp** [comment] 2024-07-26 11:27
Dear Daniel, 

I am sorry for this inconvenience, following the discussion [here](https://github.com/snap-stanford/GEARS/issues/5) we used the the git version, commit [#d6a464e40f9e759706c81edabfda8ac4bccb3a3f](https://github.com/snap-stanford/GEARS/commit/d6a464e40f9e759706c81edabfda8ac4bccb3a3f)
Locally we modified the code to get the same seeds settings, and extended information, attached is the `diff` file. 
Thank you for the interest again.
[diff.txt](https://github.com/user-attachments/files/16390914/diff.txt)

**Comment by zoepiran** [comment] 2024-07-26 11:29
Hi, 
we are sorry for this inconvenience, and thank you for the interest again! 
following the discussion [here](https://github.com/snap-stanford/GEARS/issues/5) we used the the git version, commit [#d6a464e40f9e759706c81edabfda8ac4bccb3a3f](https://github.com/snap-stanford/GEARS/commit/d6a464e40f9e759706c81edabfda8ac4bccb3a3f)
Locally we modified the code to get the same seeds settings, and extended information, attached is the [diff.txt](https://github.com/user-attachments/files/16390914/diff.txt) file.
